### ISSUE TITLE
postfix log error |  NoMethodError: undefined method `rstrip' for nil:NilClass

### ISSUE THREAD

**Issue by zodman** [mlandauer/cuttlefish#249]
```
NoMethodError: undefined method `rstrip' for nil:NilClass
/export/web/.rvm/gems/ruby-2.1.5/gems/syslog_protocol-0.9.2/lib/syslog_protocol/parser.rb:54:in `parse_hostname'
/export/web/.rvm/gems/ruby-2.1.5/gems/syslog_protocol-0.9.2/lib/syslog_protocol/parser.rb:25:in `parse'
/export/web/cuttlefish/app/models/postfix_log_line.rb:58:in `match_main_content'
/export/web/cuttlefish/app/models/postfix_log_line.rb:36:in `create_from_line'
/export/web/cuttlefish/lib/cuttlefish_log_daemon.rb:9:in `block (3 levels) in start'
/export/web/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
/export/web/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
/export/web/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.16/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
/export/web/.rvm/gems/ruby-2.1.5/gems/activerecord-4.1.16/lib/active_record/transactions.rb:208:in `transaction'
/export/web/cuttlefish/lib/cuttlefish_log_daemon.rb:8:in `block (2 levels) in start'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail.rb:205:in `call'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail.rb:205:in `read_line'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail.rb:177:in `block in tail'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail.rb:174:in `loop'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail.rb:174:in `tail'
/export/web/cuttlefish/lib/cuttlefish_log_daemon.rb:7:in `block in start'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail/logfile.rb:64:in `call'
/export/web/.rvm/gems/ruby-2.1.5/gems/file-tail-1.1.0/lib/file/tail/logfile.rb:64:in `open'
/export/web/cuttlefish/lib/cuttlefish_log_daemon.rb:6:in `start'
/export/web/cuttlefish/lib/cuttlefish_control.rb:43:in `log_start'
/export/web/cuttlefish/lib/tasks/cuttlefish.rake:11:in `block (2 levels) in <top (required)>'
/export/web/.rvm/gems/ruby-2.1.5/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/export/web/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/export/web/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => cuttlefish:log
(See full trace by running task with --trace)

```

**Comment by zodman** [comment]
this happend when someone truncate the /var/log/mail.log and put a empty line
